package com.afluffywaffle.layuv.docx

import org.json.JSONArray
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.TestFactory

/**
 * Cross-language golden test for [Anchoring]. Cases + expected outputs are
 * generated by the verbatim Dart functions in gen_engine_goldens.dart, so this
 * asserts the Kotlin locate/word-snap behaves identically (UTF-16 offsets,
 * roundToInt hint, quote normalisation, surrogate pairs).
 */
class AnchoringGoldenTest {

    @TestFactory
    fun locate(): List<DynamicTest> {
        val cases = JSONArray(resource("/golden/anchoring/locate.json"))
        return (0 until cases.length()).map { i ->
            val c = cases.getJSONObject(i)
            DynamicTest.dynamicTest("locate:${c.getString("name")}") {
                val actual = Anchoring.locateInPlain(
                    c.getString("plain"),
                    c.getString("selectedText"),
                    c.getString("prefix"),
                    c.getString("suffix"),
                    c.getDouble("positionHint"),
                )
                if (c.isNull("expected")) {
                    assertNull(actual, "expected no match")
                } else {
                    val e = c.getJSONObject("expected")
                    assertEquals(TextSpan(e.getInt("start"), e.getInt("end")), actual)
                }
            }
        }
    }

    @TestFactory
    fun wordsnap(): List<DynamicTest> {
        val cases = JSONArray(resource("/golden/anchoring/wordsnap.json"))
        return (0 until cases.length()).map { i ->
            val c = cases.getJSONObject(i)
            DynamicTest.dynamicTest("wordsnap:${c.getString("name")}") {
                val actual = Anchoring.snapToWordBoundaries(
                    c.getString("text"), c.getInt("start"), c.getInt("end"),
                )
                val e = c.getJSONObject("expected")
                assertEquals(TextSpan(e.getInt("start"), e.getInt("end")), actual)
            }
        }
    }

    private fun resource(path: String): String =
        javaClass.getResource(path)?.readText(Charsets.UTF_8)
            ?: error("missing test resource: $path (run gen_engine_goldens.dart)")
}
